### ISSUE TITLE
Cardinal3D crashes when performing beveling

### ISSUE THREAD

**Issue by kfeng19** [stanford-cs248/Cardinal3D#1]
I am working on Windows compiling with VS2022 Community.
After creating a simple cube, I tried beveling on its vertex and got the following error:

![InkedCapture_LI](https://user-images.githubusercontent.com/8847195/150724912-3d902bfe-3d60-48db-b7a7-388c644bb3f6.jpg)

**Comment by sand500** [comment]
I get a similar error in `Model::set_selected`

1. Add a cube from new object
2. Select an edge
3. Click bevel
4. Click the same edge

**Comment by kfeng19** [comment]
Seems I misunderstood our task in the beginning -- once we implement beveling this won't happen.
